pipeline {
    agent any
	tools { 
        maven 'MAVEN_HOME' 
        jdk 'JAVA_HOME' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

       stage ('Build') {
            steps {
		sh 'cd /Users/mac/.jenkins/workspace/pipeline-script@script/Automation-Master/'
		sh 'pwd'
		sh 'mvn -Dfile=/Users/mac/.jenkins/workspace/pipeline-script@script/Automation-Master/pipelinemaven.jar" "-DgroupId=Automation-Master" "-DartifactId=mavenjob" "-Dversion=1.0.0-SNAPSHOT" "-Dpackaging=jar install' 
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
    }
}