#!/usr/bin/env groovy

pipeline {
    agent any
	tools { 
        maven 'MAVEN_HOME' 
        jdk 'JAVA_HOME' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }

       stage ('Build') {
            steps {
		 dir('/Users/mac/.jenkins/workspace/pipeline-script/Automation-Master') {
            sh 'mvn test'
        }
            steps {
                    emailext body: '''$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS.<br/>
                    <br/>
                    Check console <a href="$BUILD_URL">output</a> to view full results.<br/>
                    If you cannot connect to the build server, check the attached logs.<br/>
                    <br/>
                    --<br/>
                    Following is the last 100 lines of the log.<br/>
                    <br/>
                    --LOG-BEGIN--<br/>
                    <pre style=\'line-height: 22px; display: block; color: #333; font-family: Monaco,Menlo,Consolas,"Courier New",monospace; padding: 10.5px; margin: 0 0 11px; font-size: 13px; word-break: break-all; word-wrap: break-word; white-space: pre-wrap; background-color: #f5f5f5; border: 1px solid #ccc; border: 1px solid rgba(0,0,0,.15); -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px;\'>
                    ${BUILD_LOG, maxLines=100, escapeHtml=true}
                    </pre>
                    --LOG-END--''', subject: '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!', to: 'qatestingsatu01@gmail.com'
        }
		}
         
        }
    }
}